--!strict
-- Authored placement data for the Test real grass hub.  Every entry points to
-- an approved real model in WorldAssetRegistry; no primitive visual geometry
-- is generated by this manifest.
local function at(x: number, y: number, z: number, yaw: number?): CFrame
	return CFrame.new(x, y, z) * CFrame.Angles(0, math.rad(yaw or 0), 0)
end

return {
	-- Canopy framing and discovery trail.
	{ key = "CommonTree1", name = "Tree_CareWest", pivot = at(92, 10, -226, 18), collidable = true },
	{ key = "CommonTree2", name = "Tree_CareNorth", pivot = at(111, 10, -193, -24), collidable = true },
	{ key = "CommonTree3", name = "Tree_PartyEast", pivot = at(178, 10, -251, 14), collidable = true },
	{ key = "Willow1", name = "Tree_Discovery", pivot = at(89, 10, -276, -15), collidable = true },
	{ key = "BirchTree1", name = "Tree_HatchEast", pivot = at(179, 10, -208, 12), collidable = true },

	-- Care garden.
	{ key = "TreeStump", name = "FoodTable", pivot = at(126, 10, -218, 20), collidable = true },
	{ key = "BerryBush1", name = "FoodBerryBush", pivot = at(116, 10, -215, -30), collidable = false },
	{ key = "Flowers", name = "FoodFlowers", pivot = at(121, 10, -210, 40), collidable = false },
	{ key = "MossRock1", name = "WashRockWest", pivot = at(141, 10, -213, 20), collidable = true },
	{ key = "MossRock2", name = "WashRockEast", pivot = at(149, 10, -216, -15), collidable = true },
	{ key = "Lilypad", name = "WashLilypad", pivot = at(145, 10.2, -219, 30), collidable = false },
	{ key = "WoodLogMoss", name = "PettingLog", pivot = at(122, 10, -237, 78), collidable = true },
	{ key = "GrassShort", name = "PettingGrass", pivot = at(127, 10, -237, 5), collidable = false },

	-- Hatch grove.
	{ key = "TreeStumpMoss", name = "HatchNaturalNest", pivot = at(157, 10, -207, -15), collidable = true },
	{ key = "GrassShort", name = "HatchGrassNorth", pivot = at(157, 10, -202, 35), collidable = false },
	{ key = "GrassShort", name = "HatchGrassSouth", pivot = at(160, 10, -213, -20), collidable = false },
	{ key = "Flowers", name = "HatchFlowersWest", pivot = at(151, 10, -209, 90), collidable = false },
	{ key = "Flowers", name = "HatchFlowersEast", pivot = at(164, 10, -205, -60), collidable = false },

	-- Party boundary and seating garden.
	{ key = "WoodLog", name = "PartyBoundaryWest", pivot = at(116, 10, -268, 90), collidable = true },
	{ key = "WoodLog", name = "PartyBoundaryEast", pivot = at(156, 10, -268, 90), collidable = true },
	{ key = "Rock1", name = "PartyRockNW", pivot = at(113, 10, -248, 25), collidable = true },
	{ key = "Rock2", name = "PartyRockNE", pivot = at(159, 10, -248, -35), collidable = true },
	{ key = "Bush1", name = "PartyBushWest", pivot = at(108, 10, -259, 30), collidable = false },
	{ key = "Bush2", name = "PartyBushEast", pivot = at(165, 10, -259, -15), collidable = false },

	-- Hidden egg trail.
	{ key = "MossRock2", name = "DiscoveryRock", pivot = at(101, 10, -280, 65), collidable = true },
	{ key = "BerryBush1", name = "DiscoveryBush", pivot = at(96, 10, -276, -20), collidable = false },
	{ key = "Flowers", name = "DiscoveryFlowers", pivot = at(104, 10, -274, 12), collidable = false },
}
